---
title: "Assignment2"
author: "Daphne Jacobsberg"
date: "9/30/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

My Own Code

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F)
```


```{r}
library(tidyverse)
library(sf)
library(tigris)
library(censusapi)
library(mapview)
library(devtools)

Sys.setenv(CENSUS_KEY="c8aa67e4086b4b5ce3a8717f59faa9a28f611dab")
```



california = 06
santa clara = 085
cupertino

Only to find variables
```{r}
dec_vars_2020 <-
  listCensusMetadata(
    name = "2020/dec/pl",
    type = "variables"
  )

dec_vars_2010 <-
  listCensusMetadata(
    name = "2010/dec/pl",
    type = "variables"
  )
```

Get data
```{r}
scc_pop_2020 <-
  getCensus(
    name = "dec/pl",
    vintage = 2020,
    region = "block:*", 
    regionin = "state:06+county:085",
    vars = "P1_003N"
  ) %>% 
  transmute(
    block =
      paste0(state,county,tract,block),
    pop = P1_003N
  )
```

```{r}
scc_pop_2010 <-
  getCensus(
    name = "dec/pl",
    vintage = 2010,
    region = "block:*", 
    regionin = "state:06+county:085",
    vars = "P001003"
  ) %>% 
  transmute(
    block =
      paste0(state,county,tract,block),
    pop = P001003
  )
```


Not sure I need this
```{r}
ca_counties <- counties("CA", cb = T, progress_bar = F)

st_crs(ca_counties)

projection <- "+proj=utm +zone=10 +ellps=GRS80 +datum=NAD83 +units=ft +no_defs"

ca_counties_transformed <- 
  ca_counties %>% 
  st_transform(4326) %>% 
  st_transform(26910) %>% 
  st_transform(projection) %>% 
  st_transform(st_crs(ca_counties))

bay_county_names <-
  c(
    "Alameda",
    "Contra Costa",
    "Marin",
    "Napa",
    "San Francisco",
    "San Mateo",
    "Santa Clara",
    "Solano",
    "Sonoma"
  )

bay_counties <-
  counties("CA", cb = T, progress_bar = F) %>%
  filter(NAME %in% bay_county_names)






bay_cities <- ca_cities[bay_counties, ]

bay_cities_within <-
  ca_cities %>% 
  st_centroid() %>% 
  .[bay_counties, ] %>% 
  st_set_geometry(NULL) %>% 
  left_join(ca_cities %>% select(GEOID)) %>% 
  st_as_sf()

bay_cities_within <-
  ca_cities[which(ca_cities$GEOID %in% st_centroid(ca_cities)[bay_counties, ]$GEOID), ]

scc_cbgs <- block_groups("CA", bay_county_names[7], cb = T, progress_bar = F)

bay_cbgs <- 
  bay_county_names %>% 
  map_dfr(function(county) {
    block_groups("CA", "Santa Clara", cb = T, progress_bar = F)
  })




```


Keep this
```{r}

scc_blocks_2020 <- blocks("CA", "Santa Clara", year = 2020, progress_bar = F)
scc_blocks_2010 <- blocks("CA", "Santa Clara", year = 2010, progress_bar = F)

cup_boundary <- places("CA", progress_bar = F) %>% 
  filter(NAME == "Cupertino")

cup_pop_2020 <- scc_pop_2020 %>% 
  left_join(scc_blocks_2020 %>% select(block = GEOID20)) %>% 
  st_as_sf() %>% 
  st_centroid() %>% 
  .[cup_boundary, ] %>% 
  st_set_geometry(NULL) %>% 
  left_join(scc_blocks_2020 %>% select(block = GEOID20)) %>% 
  st_as_sf()


cup_pop_2010 <- scc_pop_2010 %>% 
  left_join(scc_blocks_2010 %>% select(block = GEOID10)) %>% 
  st_as_sf() %>% 
  st_centroid() %>% 
  .[cup_boundary, ] %>% 
  st_set_geometry(NULL) %>% 
  left_join(scc_blocks_2010 %>% select(block = GEOID10)) %>% 
  st_as_sf()


```


```{r}
bay_pdas <- st_read("https://opendata.arcgis.com/datasets/4df9cb38d77346a289252ced4ffa0ca0_0.geojson")

scc_pdas <-
  bay_pdas %>% 
  filter(county == "Santa Clara") %>% 
  st_transform(4269)

scc_pdas_blocks <- smc_blocks_2020[scc_pdas, ]


scc_pdas_blocks_area <-
  scc_pdas_blocks %>% 
  st_transform(26910) %>% 
  mutate(area = st_area(.))

scc_pdas_blocks_intersection <-
  scc_pdas_blocks_area %>% 
  st_intersection(
    scc_pdas %>% 
      st_transform(26910)
  )

scc_pdas_blocks_3 <-
  scc_pdas_blocks %>% 
  select(block = GEOID20) %>% 
  left_join(scc_pop_2020) %>% 
  st_transform(26910) %>% 
  mutate(original_area = st_area(.)) %>% 
  st_intersection(
    scc_pdas %>% 
      st_transform(26910)
  ) %>% 
  mutate(
    leftover_area = st_area(.),
    perc_area = leftover_area / original_area,
    pop = pop * perc_area
  )

```










2.1 Geospatial Data
```{r}
ca_counties <- counties("CA", cb = T, progress_bar = F)

st_crs(ca_counties)
```

```{r}
projection <- "+proj=utm +zone=10 +ellps=GRS80 +datum=NAD83 +units=ft +no_defs"

ca_counties_transformed <- 
  ca_counties %>% 
  st_transform(4326) %>% 
  st_transform(26910) %>% 
  st_transform(projection) %>% 
  st_transform(st_crs(ca_counties))
```

Three map plotting options below:
```{r}
ggplot(ca_counties) + geom_sf()
```

```{r}
mapview(ca_counties)
```

```{r}
leaflet() %>% 
  addTiles() %>% 
  addPolygons(
    data = ca_counties
  ) %>%
  addMarkers(
    data = ca_counties %>% 
      st_centroid()
  )
```

Filtering for the Bay Area:
```{r}
bay_county_names <-
  c(
    "Alameda",
    "Contra Costa",
    "Marin",
    "Napa",
    "San Francisco",
    "San Mateo",
    "Santa Clara",
    "Solano",
    "Sonoma"
  )

bay_counties <-
  counties("CA", cb = T, progress_bar = F) %>%
  filter(NAME %in% bay_county_names)

#plotting
ggplot(bay_counties) + geom_sf()
```

```{r}
ca_cities <- places("CA", cb = T, progress_bar = FALSE)

bay_cities <- ca_cities[bay_counties, ]

#plotting
mapview(bay_counties, alpha.regions = 0) + mapview(bay_cities)
```

Same idea but filtered not to include cities on border
```{r}
bay_cities_within <-
  ca_cities %>% 
  st_centroid() %>% 
  .[bay_counties, ] %>% 
  st_set_geometry(NULL) %>% 
  left_join(ca_cities %>% select(GEOID)) %>% 
  st_as_sf()

#plotting
mapview(bay_counties, alpha.regions = 0) + mapview(bay_cities_within, label = "NAME")
```

This shows the cities that were removed
```{r}
leaflet() %>% 
  addTiles() %>% 
  addPolygons(
    data = bay_counties,
    fill = F,
    weight = 2,
    label = ~NAME
  ) %>%
  addPolygons(
    data = bay_cities %>% 
      filter(!GEOID %in% bay_cities_within$GEOID),
    color = "red",
    label = ~NAME
  ) %>% 
  addPolygons(
    data = bay_cities_within,
    color = "green",
    label = ~NAME
  )
```

census block groups (CBGs)
```{r}
bay_cbgs <- block_groups("CA", bay_county_names[1:9], cb = T, progress_bar = F)

#or

#bay_cbgs <- 
#  bay_county_names %>% 
#  map_dfr(function(county) {
#    block_groups("CA", county, cb = T, progress_bar = F)
#  })

bay_cbgs_clip <- st_read("https://opendata.arcgis.com/datasets/037fc1597b5a4c6994b89c46a8fb4f06_0.geojson")

ggplot(bay_cbgs_clip)+geom_sf()
```

Zips
```{r}
usa_zips <- 
  zctas(cb = T, progress_bar = F)

bay_zips <-
  usa_zips %>% 
  st_centroid() %>% 
  .[bay_counties, ] %>% 
  st_set_geometry(NULL) %>% 
  left_join(usa_zips %>% select(GEOID10)) %>% 
  st_as_sf()

```


```{r}
res_pal <- colorNumeric(
  palette = "Reds",
  domain = 
    pge_20_res_elec$TOTALKWH
)

leaflet() %>% 
  addTiles() %>% 
  addPolygons(
    data = pge_20_res_elec,
    fillColor = ~res_pal(TOTALKWH),
    color = "white",
    opacity = 0.5,
    fillOpacity = 0.5,
    weight = 1,
    label = ~paste0(
      round(TOTALKWH), 
      " kWh total in ",
      ZIPCODE
    ),
    highlightOptions = highlightOptions(
      weight = 2,
      opacity = 1
    )
  ) %>% 
  addLegend(
    data = pge_20_res_elec,
    pal = res_pal,
    values = ~TOTALKWH,
    title = "Total Residential<br>kWh, 2020"
  )
```

```{r}
ca_tracts <- tracts("CA", cb = T, progress_bar = F)

bay_phys_health_18 <-
  health_ca %>% 
  filter(
    Measure == "Physical health not good for >=14 days among adults aged >=18 years",
    Year == 2018
  ) %>% 
  left_join(
    ca_tracts %>% select(GEOID),
    by = c("LocationName" = "GEOID")
  ) %>% 
  st_as_sf() %>% 
  st_centroid() %>% 
  .[bay_counties, ] %>% 
  st_set_geometry(NULL) %>% 
  left_join(
    ca_tracts %>% select(GEOID),
    by = c("LocationName" = "GEOID")
  ) %>% 
  st_as_sf()
```

```{r}
health_pal <- colorNumeric(
  palette = "Purples",
  domain = 
    bay_phys_health_18$Data_Value
)

leaflet() %>% 
  addTiles() %>% 
  addPolygons(
    data = bay_phys_health_18,
    fillColor = ~health_pal(Data_Value),
    color = "white",
    opacity = 0.5,
    fillOpacity = 0.75,
    weight = 1,
    label = ~paste0(
      round(Data_Value), 
      "% in ",
      LocationName
    ),
    highlightOptions = highlightOptions(
      weight = 2,
      opacity = 1
    )
  ) %>% 
  addLegend(
    data = bay_phys_health_18,
    pal = health_pal,
    values = ~Data_Value,
    title = "Physical health<br>not good for 14+ days<br>among adults aged<br>18+ years, 2018"
  )
```

2.2 ACS Data

```{r}
acs_vars_2019_5yr <-
  listCensusMetadata(
    name = "2019/acs/acs5",
    type = "variables"
  )
```

```{r}
smc_sexbyage <-
  getCensus(
    name = "acs/acs5",
    vintage = 2019,
    region = "block group:*", 
    regionin = "state:06+county:081",
    vars = "group(B01001)"
  ) %>%
  mutate(
    cbg =
      paste0(state,county,tract,block_group)
  ) %>% 
  select(!c(GEO_ID,state,county,tract,block_group,NAME) & !ends_with(c("EA","MA","M"))) %>%
  pivot_longer(
    ends_with("E"),
    names_to = "variable",
    values_to = "estimate"
  ) %>%
  left_join(
    acs_vars_2019_5yr %>% 
      select(name, label), 
    by = c("variable" = "name")
  ) %>% 
  select(-variable) %>% 
  separate(
    label,
    into = c(NA,NA,"sex","age"),
    sep = "!!"
  ) %>% 
  filter(!is.na(age))
```

```{r}
smc_elderly <- 
  smc_sexbyage %>% 
  mutate(
    elderly = 
      ifelse(
        age %in% c(
          "65 and 66 years",
          "67 to 69 years",
          "70 to 74 years",
          "75 to 79 years",
          "80 to 84 years",
          "85 years and over"
        ),
        estimate,
        NA
      )
  ) %>% 
  group_by(cbg) %>% 
  summarize(
    elderly = sum(elderly, na.rm = T),
    total_pop = sum(estimate, na.rm = T)
  ) %>% 
  mutate(
    percent_elderly = elderly/total_pop*100
  ) %>% 
  filter(!is.na(percent_elderly))
```

Maps:
```{r}
smc_blockgroups <- block_groups("CA", "San Mateo", cb = T, progress_bar = F)

elderly_pal <- colorNumeric(
  palette = "Blues",
  domain = 
    smc_elderly$percent_elderly
)

leaflet() %>% 
  addProviderTiles(provider = providers$CartoDB.Positron) %>% 
  addPolygons(
    data = 
      smc_elderly %>% 
        left_join(
          smc_blockgroups %>% select(GEOID), 
          by = c("cbg" = "GEOID")
        ) %>% 
        st_as_sf(),
    fillColor = ~elderly_pal (percent_elderly),
    color = "white",
    opacity = 0.5,
    fillOpacity = 0.75,
    weight = 1,
    label = ~paste0(
      round(percent_elderly), 
      "% over age 65"
    ),
    highlightOptions = highlightOptions(
      weight = 2,
      opacity = 1
    )
  ) %>% 
  addLegend(
    data = smc_elderly,
    pal = elderly_pal,
    values = ~percent_elderly,
    title = "% over 65"
  )
```


2.3 Decennial Data

```{r}
smc_pop_2020 <-
  getCensus(
    name = "dec/pl",
    vintage = 2020,
    region = "block:*", 
    regionin = "state:06+county:081",
    vars = "P1_001N"
  ) %>% 
  transmute(
    block =
      paste0(state,county,tract,block),
    pop = P1_001N
  )
```

```{r}
dec_vars_2020 <-
  listCensusMetadata(
    name = "2020/dec/pl",
    type = "variables"
  )

smc_pop_race_2020 <-
  getCensus(
    name = "dec/pl",
    vintage = 2020,
    region = "block:*", 
    regionin = "state:06+county:081",
    vars = "group(P1)"
  ) %>% 
  mutate(
    block =
      paste0(state,county,tract,block)
  ) %>% 
  select(!c(GEO_ID,state,county,tract,NAME) & !ends_with(c("NA"))) %>% 
  pivot_longer(
    ends_with("N"),
    names_to = "name",
    values_to = "estimate"
  ) %>%
  left_join(
    dec_vars_2020 %>% 
      select(name, label)
  ) %>% 
  select(-name) %>% 
  separate(
    label,
    into = c(NA,NA,"category1","category2"),
    sep = "!!"
  )
```

```{r}
smc_blocks_2020 <- blocks("CA", "San Mateo", year = 2020, progress_bar = F)

nfo_boundary <- places("CA", progress_bar = F) %>% 
  filter(NAME == "North Fair Oaks")

nfo_pop_2020 <- smc_pop_2020 %>% 
  left_join(smc_blocks_2020 %>% select(block = GEOID20)) %>% 
  st_as_sf() %>% 
  st_centroid() %>% 
  .[nfo_boundary, ] %>% 
  st_set_geometry(NULL) %>% 
  left_join(smc_blocks_2020 %>% select(block = GEOID20)) %>% 
  st_as_sf()

mapview(nfo_pop_2020, zcol = "pop")
```






























